model:
  model_name: TOMCAT
  prompt_template:
  - a photo of x x
  ctx_init:
  - 'a photo of '
  clip_model: ViT-L/14
  clip_arch: /root/tomcat/TOMCAT/clip/ViT-L-14.pt
  adapter_dim: 64
  adapter_dropout: 0.1
  comp_cls_loss_weight: 1
  use_adapter: true
train:
  dataset: ut-zappos
  dataset_path: /root/tomcat/TOMCAT/download_data/data/ut-zappos
  optimizer: Adam
  scheduler: StepLR
  step_size: 5
  gamma: 0.5
  lr: 0.0005
  attr_dropout: 0.3
  weight_decay: 1.0e-05
  context_length: 10
  train_batch_size: 32
  gradient_accumulation_steps: 4
  seed: 0
  epochs: 100
  epoch_start: 0
  val_metric: best_AUC
  save_final_model: true
  use_mixed_precision: true
test:
  eval_batch_size_wo_tta: 1
  eval_batch_size: 1
  topk: 1
  text_encoder_batch_size: 1024
  open_world: false
  threshold: null
  threshold_trials: 6
  bias: 0.001
  text_first: true
  num_workers: 0
  current_epoch: -1
  use_wandb: true
  seed: 42
tta:
  shot_capacity: 3
  cpu_cache: false
  eps: 0.001
  wd: 0.001
  alpha: 0
  beta: 7.5
  theta: 1
  text_lr: 5.0e-06
  image_lr: 5.0e-06
  align_loss_weight: 3.5
  use_tta: true
  use_img_cache: false
  use_align_loss: true
  lambda_orth: 0.01
  hier_theta: 0.9
  use_robust_cache: false
  correction_interval: 20
  sim_threshold: 0.2
others:
  device: cuda:0
  save_path: ./result/ut-zappos/20250305_2
  load_model: ./result/ut-zappos/20250305_2/test_best.pt
  load_model_path: ./result/ut-zappos/20250305_2
  wandb_net: online
  use_wandb: true
